project 'JGScrollViewNested.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'JGScrollViewNested' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JGScrollViewNested


   pod 'FDFullscreenPopGesture', '1.1'
   pod 'MJRefresh','3.1.12'
   pod 'MBProgressHUD', '~> 1.0.0' 
   pod 'Masonry','1.0.2'
   
   
   
  target 'JGScrollViewNestedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JGScrollViewNestedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
